### ISSUE TITLE
Print Error

### ISSUE THREAD

**Issue by rafaelsilva1406** [EddyVerbruggen/nativescript-star-printer#15]
Hello, I followed the setup and I am able to execute mostly all starPrinter methods also was able to see portName but for some reason when I run print method I receive console issue. If you encounter this before please let me know.
My Source Code
`export class DriverComponent {
    private starPrinter:StarPrinter;
    public printers: ObservableArray<SPPrinter> = new ObservableArray<SPPrinter>();
    public constructor() {
        this.starPrinter = new StarPrinter();
    }

    ngOnInit() : void {
        Bluetooth.isBluetoothEnabled().then(
            (enable) => {
                if(!enable) {
                    dialogs.alert("Bluetooth Error: Turn on Bluetooth");
                } else {
                    dialogs.confirm({
                        title: "Test Print",
                        message: "Please setup device & printer pair before proceeding",
                        okButtonText: "Start Print",
                        cancelButtonText: "Cancel"
                    }).then(res => {
                        this.starPrinter.searchPrinters().then(
                        (printers: Array<SPPrinter>) => {
                            this.printers.push(printers);
                            this.printReceipt();
                        });
                    });
                }
            });
    }

    public printReceipt(): void {
         let cmds = new SPCommands();
            cmds.setFont("smaller")
            cmds.alignCenter()
            cmds.text("Hello World!").newLine()
            cmds.newLine()
            cmds.cutPaper();
            
         this.starPrinter.print({
                portName: this.printers.getItem(0).portName,
                commands: cmds
            }).then(res => {
                console.log(res);
            });
    }
}`
Exception Message
_ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
JS:     com.starmicronics.stario.a.f(Unknown Source:232)
JS:     com.starmicronics.stario.a.<init>(Unknown Source:38)
JS:     com.starmicronics.stario.StarIOPort.getPort(Unknown Source:211)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:983)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:967)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:959)
_

**Comment by EddyVerbruggen** [comment]
Never seen it. 

Remove the printers array and pass the printer object to printreceipt. And you’re not using the fluent interface of SPCommands although the lack of ‘;’ seems to suggest you want to.

**Comment by rafaelsilva1406** [comment]
Ok, altered my code and getting different issue now.

`export class DriverComponent {
    private portName:string = "BT:Star Micronics";
    private starPrinter:StarPrinter;
    public printers: ObservableArray<SPPrinter> = new ObservableArray<SPPrinter>();
    public constructor() {
        this.starPrinter = new StarPrinter();
    }

    ngOnInit() : void {
        Bluetooth.isBluetoothEnabled().then(
            (enable) => {
                if(!enable) {
                    dialogs.alert("Bluetooth Error: Turn on Bluetooth");
                } else {
                    this.starPrinter.connect({
                        portName: this.portName 
                    }).then((res: SPPrinterStatusResult) => {
                        this.printReceipt();
                    });
                }
            });
    }

    public printReceipt(): void {
         let cmds = new SPCommands()
            .setFont("smaller")
            .alignCenter()
            .text("Hello World!").newLine()
            .newLine()
            .cutPaper();
            
         this.starPrinter.print({
                portName: this.portName,
                commands: cmds
            }).then(res => {
                console.log(res);
            });
    }
}`

> Dynamically loading class com.starmicronics.starioextension.s was unsuccessful. Will attempt to load class from alternative ClassLoader.
JS: ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
JS:     com.starmicronics.stario.a.f(Unknown Source:232)
JS:     com.starmicronics.stario.a.<init>(Unknown Source:38)
JS:     com.starmicronics.stario.StarIOPort.getPort(Unknown Source:211)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:983)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:967)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:959)
JS:     com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:17)
JS:     android.view.View.performClick(View.java:6259)
JS:     android.view.View$PerformClick.run(View.java:24732)
JS:     android.os.Handler.handleCallback(Handler.java:789)
JS:     android.os.Handler.dispatchMessage(Handler.ja...

any thoughts... Also please not the printer I am using will always connect through "BT" and only one should always be available

**Comment by EddyVerbruggen** [comment]
That's what the demo app embedded in the repo expects as well - doesn't that work correctly for you? If so, you may be able to borrow some code.

**Comment by rafaelsilva1406** [comment]
I installed the plugin to my project using the nativescript market. Not downloading the git source. I have been following the demo app just alter a few things. Let me keep poking through the. You should have two demo's one using the original source and the other installing from nativescript market place.

Please see below copy of the printer device I am using.
![img_20180904_124046836](https://user-images.githubusercontent.com/3414904/45053863-1d411480-b040-11e8-997b-2b1e7b312eb3.jpg)

**Comment by rafaelsilva1406** [comment]
I was able to get more sense of the issue by adding the reject function on promise return for the print method. Looks like I am getting timeout "Error: com.starmicronics.stario.StarIOPortException: There was no response of the printer within the timeout period". Not sure if maybe the settings are off on the printer itself.

**Comment by rafaelsilva1406** [comment]
Solved... My fault didn't have the EMU = StarPRNT. Thank You for your time. Great Library!!!
