### ISSUE TITLE
Printing not working with demo + TSP100III

### ISSUE THREAD

**Issue by acrollet** [EddyVerbruggen/nativescript-star-printer#23]
I've installed the demo (using the ns6 PR I just submitted) and have a TSP100III printer. I can connect and view status, but it will not print. There are no console errors of any kind. Any ideas of what to poke at? thanks!

**Comment by EddyVerbruggen** [comment]
I have no idea.. if I had such a printer I would happily take a look though.

**Comment by acrollet** [comment]
This is actually a duplicate of #4
