### ISSUE TITLE
Star SDK inclusion Legal?

### ISSUE THREAD

**Issue by NathanaelA** [EddyVerbruggen/nativescript-star-printer#3]
You might want to double check the sdk agreement, I'm pretty sure that you are NOT allowed to distribute the Star SDK except in a compiled application.    They don't really like you distributing something that they will be updating and having older copies out in the wild.

**Comment by EddyVerbruggen** [comment]
If there is a problem I expect them to contact me and I'll deal with it. My email address is on my GitHub profile page.
