### ISSUE TITLE
NativeScript 8 support

### ISSUE THREAD

**Issue by asharghi** [EddyVerbruggen/nativescript-star-printer#31]
Hi @EddyVerbruggen. Any chance of migrating this plugin to ns 8?

**Comment by EddyVerbruggen** [comment]
Yep, but to give me a head-start, can you share what the problem is on NS8?

**Comment by asharghi** [comment]
I haven't tried it yet, but one of my apps that I wish to migriate to ns8 uses this plugin. I imagine the imports of tns-core-module will be an issue in this plugin. For example: import {ImageSource} from "tns-core-modules/image-source" in star-printer.common.ts

**Comment by EddyVerbruggen** [comment]
OK, version 4.0.0 has now been published to npm, which should work fine with NativeScript 7 and up.

**Comment by asharghi** [comment]
That was fast, thanks a lot! One more question if I can ask. I really need this to work on iOS. Issue: https://github.com/EddyVerbruggen/nativescript-star-printer/issues/21 

You are probably busy with a lot of other stuff so I want to donate for your time. I can also pay for the printer if you need to buy the SM-L200 printer to debug this.
