### ISSUE TITLE
Add into Angular 4 App

### ISSUE THREAD

**Issue by fwidtmann** [EddyVerbruggen/nativescript-star-printer#8]
Hi, 
is it possible to add your plugin into our angular 4 application?

background:
we want to print(star sm-230i) via bluetooth from our angular4 app. (google chrome to star printer via bluetooth).
we dont want to use this WebPRNT-Browser (http://www.starmicronics.com/pages/WebPRNT-Browser)

**Comment by EddyVerbruggen** [comment]
If you’re using NativeScript: yes.
